[book]
authors = ["J. Simon Richard", "David Awkar", "Veer Gaudani"]
language = "en"
multilingual = false
src = "src"
title = "The CPT's Game Development Workshop"

[output.html]
additional-css = ["theme/style.css"]