name: GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'workshop-book/**'
      - '.github/workflows/publish.yml'
  pull_request:
    paths:
      - 'workshop-book/**'
      - '.github/workflows/publish.yml'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      contents: write  # This allows pushing to the repo
      pages: write     # This allows deploying to Pages
      id-token: write  # This is required for Pages deployment
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: cd workshop-book && mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./workshop-book/book